/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.movlad.semviz.view;

import com.jogamp.opengl.awt.GLJPanel;
import com.movlad.semviz.application.CommandNavigationController;
import com.movlad.semviz.application.SQMController;
import com.movlad.semviz.application.SceneController;
import com.movlad.semviz.core.sqm.SQM;
import com.movlad.semviz.core.sqm.SemanticCloudDescription;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

public class MainFrame extends javax.swing.JFrame implements PropertyChangeListener {

    private SQMController sqmController;
    private CommandNavigationController navigationController;
    private SceneController sceneController;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_GeometrySelection;
    private javax.swing.JLabel Label_GeometrySelection;
    private java.awt.Label Label_Individuals;
    private javax.swing.JLabel Label_StatusText;
    private javax.swing.JLabel Label_VarInfo;
    private javax.swing.JList<String> List_Individuals;
    private javax.swing.JPanel Panel_Control;
    private javax.swing.JPanel Panel_GLContainer;
    private javax.swing.JPanel Panel_GeometrySelection;
    private javax.swing.JPanel Panel_Individuals;
    private javax.swing.JPanel Panel_Status;
    private javax.swing.JPanel Panel_VarInfo;
    private javax.swing.JScrollPane Scroll_Individuals;
    private javax.swing.JScrollPane Scroll_VarInfo;
    private javax.swing.JTable Table_VarInfo;
    private javax.swing.JTextField TextField_Command;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItem_Open;
    private javax.swing.JMenuItem menuItem_Quit;
    private javax.swing.JMenu menu_File;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form MainWindow
     */
    public MainFrame() {
        initComponents();
        initControllers();
        initStatusBar();
        initIndividualsList();
        initVarInfoTable();
        initViewerPanel();
        initGeometrySelectionComboBox();
        initCommandTextField();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */

        if (System.getProperty("os.name").contains("Windows")) {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MainFrame mainWindow = new MainFrame();

            mainWindow.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    mainWindow.exit();
                }
            });

            mainWindow.setExtendedState(JFrame.MAXIMIZED_BOTH);
            mainWindow.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
            mainWindow.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextField_Command = new javax.swing.JTextField();
        Panel_Control = new javax.swing.JPanel();
        Panel_Status = new javax.swing.JPanel();
        Label_StatusText = new javax.swing.JLabel();
        Panel_Individuals = new javax.swing.JPanel();
        Label_Individuals = new java.awt.Label();
        Scroll_Individuals = new javax.swing.JScrollPane();
        List_Individuals = new javax.swing.JList<>();
        Panel_VarInfo = new javax.swing.JPanel();
        Label_VarInfo = new javax.swing.JLabel();
        Scroll_VarInfo = new javax.swing.JScrollPane();
        Table_VarInfo = new javax.swing.JTable();
        Panel_GeometrySelection = new javax.swing.JPanel();
        Label_GeometrySelection = new javax.swing.JLabel();
        ComboBox_GeometrySelection = new javax.swing.JComboBox<>();
        Panel_GLContainer = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menu_File = new javax.swing.JMenu();
        menuItem_Open = new javax.swing.JMenuItem();
        menuItem_Quit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextField_Command.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TextField_Command.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField_CommandKeyPressed(evt);
            }
        });

        Panel_Control.setBackground(new java.awt.Color(204, 204, 204));

        Label_StatusText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Label_StatusText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_StatusText.setText("Ontology Model Loaded");
        Label_StatusText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Panel_Individuals.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Label_Individuals.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Label_Individuals.setText("Cloud List");

        List_Individuals.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        List_Individuals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        List_Individuals.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                List_IndividualsValueChanged(evt);
            }
        });
        Scroll_Individuals.setViewportView(List_Individuals);

        javax.swing.GroupLayout Panel_IndividualsLayout = new javax.swing.GroupLayout(Panel_Individuals);
        Panel_Individuals.setLayout(Panel_IndividualsLayout);
        Panel_IndividualsLayout.setHorizontalGroup(
            Panel_IndividualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_IndividualsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(Panel_IndividualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_IndividualsLayout.createSequentialGroup()
                        .addComponent(Label_Individuals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Scroll_Individuals))
                .addContainerGap())
        );
        Panel_IndividualsLayout.setVerticalGroup(
            Panel_IndividualsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_IndividualsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Individuals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Scroll_Individuals, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        Label_VarInfo.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Label_VarInfo.setText("Queried Info");

        Table_VarInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Scroll_VarInfo.setViewportView(Table_VarInfo);

        javax.swing.GroupLayout Panel_VarInfoLayout = new javax.swing.GroupLayout(Panel_VarInfo);
        Panel_VarInfo.setLayout(Panel_VarInfoLayout);
        Panel_VarInfoLayout.setHorizontalGroup(
            Panel_VarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_VarInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_VarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Scroll_VarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(Panel_VarInfoLayout.createSequentialGroup()
                        .addComponent(Label_VarInfo)
                        .addGap(0, 178, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_VarInfoLayout.setVerticalGroup(
            Panel_VarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_VarInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_VarInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Scroll_VarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Label_GeometrySelection.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Label_GeometrySelection.setText("View");

        ComboBox_GeometrySelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBox_GeometrySelection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBox_GeometrySelectionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout Panel_GeometrySelectionLayout = new javax.swing.GroupLayout(Panel_GeometrySelection);
        Panel_GeometrySelection.setLayout(Panel_GeometrySelectionLayout);
        Panel_GeometrySelectionLayout.setHorizontalGroup(
            Panel_GeometrySelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_GeometrySelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_GeometrySelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBox_GeometrySelection, 0, 252, Short.MAX_VALUE)
                    .addGroup(Panel_GeometrySelectionLayout.createSequentialGroup()
                        .addComponent(Label_GeometrySelection, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_GeometrySelectionLayout.setVerticalGroup(
            Panel_GeometrySelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_GeometrySelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_GeometrySelection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBox_GeometrySelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_StatusLayout = new javax.swing.GroupLayout(Panel_Status);
        Panel_Status.setLayout(Panel_StatusLayout);
        Panel_StatusLayout.setHorizontalGroup(
            Panel_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Individuals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_VarInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_GeometrySelection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_StatusText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_StatusLayout.setVerticalGroup(
            Panel_StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_StatusLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Label_StatusText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_Individuals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_VarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Panel_GeometrySelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel_ControlLayout = new javax.swing.GroupLayout(Panel_Control);
        Panel_Control.setLayout(Panel_ControlLayout);
        Panel_ControlLayout.setHorizontalGroup(
            Panel_ControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panel_ControlLayout.setVerticalGroup(
            Panel_ControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Panel_GLContainer.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout Panel_GLContainerLayout = new javax.swing.GroupLayout(Panel_GLContainer);
        Panel_GLContainer.setLayout(Panel_GLContainerLayout);
        Panel_GLContainerLayout.setHorizontalGroup(
            Panel_GLContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        Panel_GLContainerLayout.setVerticalGroup(
            Panel_GLContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menu_File.setText("File");

        menuItem_Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuItem_Open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-opened-folder-16.png"))); // NOI18N
        menuItem_Open.setText("Open");
        menuItem_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_OpenActionPerformed(evt);
            }
        });
        menu_File.add(menuItem_Open);

        menuItem_Quit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuItem_Quit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-exit-16.png"))); // NOI18N
        menuItem_Quit.setText("Exit");
        menuItem_Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_QuitActionPerformed(evt);
            }
        });
        menu_File.add(menuItem_Quit);

        menuBar.add(menu_File);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TextField_Command)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_Control, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_GLContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Panel_GLContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Panel_Control, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_Command, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItem_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_OpenActionPerformed
        final JFileChooser fc = new JFileChooser();

        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String path = fc.getSelectedFile().getAbsolutePath();

            sqmController.load(path);
        }
    }//GEN-LAST:event_menuItem_OpenActionPerformed

    private void menuItem_QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_QuitActionPerformed
        exit();
    }//GEN-LAST:event_menuItem_QuitActionPerformed

    private void TextField_CommandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CommandKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                String queryString = TextField_Command.getText();
                navigationController.enter(queryString);

                break;
            case KeyEvent.VK_UP:
                navigationController.up();

                break;
            case KeyEvent.VK_DOWN:
                navigationController.down();

                break;
        }
    }//GEN-LAST:event_TextField_CommandKeyPressed

    private void ComboBox_GeometrySelectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBox_GeometrySelectionItemStateChanged
        int itemIndex = List_Individuals.getSelectedIndex();
        int geometryIndex = ComboBox_GeometrySelection.getSelectedIndex();

        if (itemIndex != -1) {
            sceneController.setSelectedViewIndex(itemIndex, geometryIndex);
        }
    }//GEN-LAST:event_ComboBox_GeometrySelectionItemStateChanged

    private void List_IndividualsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_List_IndividualsValueChanged
        int index = List_Individuals.getSelectedIndex();

        sqmController.setSelectedDescriptionIndex(index);
    }//GEN-LAST:event_List_IndividualsValueChanged

    private void initControllers() {
        sqmController = SQMController.getInstance();
        navigationController = new CommandNavigationController();
        sceneController = new SceneController();

        sqmController.register(this);
        navigationController.register(this);
        sceneController.register(this);
    }

    private void initStatusBar() {
        Label_StatusText.setText("No directory loaded.");
        Label_StatusText.setToolTipText("");
    }

    private void initIndividualsList() {
        DefaultListModel model = new DefaultListModel();

        List_Individuals.setModel(model);
        List_Individuals.getSelectionModel().setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);
    }

    private void initVarInfoTable() {
        DefaultTableModel varInfoTableModel = new DefaultTableModel();
        Table_VarInfo.setModel(varInfoTableModel);

        varInfoTableModel.addColumn("Variable");
        varInfoTableModel.addColumn("Value");
    }

    private void initGeometrySelectionComboBox() {
        ComboBox_GeometrySelection.setEnabled(false);
        ComboBox_GeometrySelection.removeAllItems();

        ComboBox_GeometrySelection.addItem("High Resolution");
        ComboBox_GeometrySelection.addItem("High Resolution (Normals)");
        ComboBox_GeometrySelection.addItem("Convex Hull");
    }

    private void initViewerPanel() {
        GLJPanel panel = new ViewerPanel(Panel_GLContainer.getSize(), sceneController);

        Panel_GLContainer.add(panel);
        Panel_GLContainer.addComponentListener(new ComponentAdapter() {

            @Override
            public void componentResized(ComponentEvent e) {
                panel.setSize(Panel_GLContainer.getSize());
            }

        });

        panel.setVisible(true);
    }

    private void initCommandTextField() {
        TextField_Command.setEnabled(false);
    }

    private void resetInterface() {
        resetGeometrySelectionComboBox();
        resetVarInfoTable();
        resetIndividualsList();
        initStatusBar();
        sceneController.resetDisplayInformation();

        TextField_Command.setText("");
        TextField_Command.setEnabled(false);
    }

    private void resetVarInfoTable() {
        DefaultTableModel model = (DefaultTableModel) Table_VarInfo.getModel();

        model.setRowCount(0);
    }

    private void resetIndividualsList() {
        DefaultListModel listModel = (DefaultListModel) List_Individuals.getModel();

        listModel.clear();
        sceneController.setDisplaySelection(-1);
    }

    private void resetGeometrySelectionComboBox() {
        ComboBox_GeometrySelection.setSelectedIndex(0);
        ComboBox_GeometrySelection.setEnabled(false);
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().contains("Error")) {
            JOptionPane.showMessageDialog(this, evt.getNewValue(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

        pollSQMEvents(evt);
        pollNavigationEvents(evt);
    }

    /**
     * Checks whether an event comes from the {@code SQMController} and takes
     * action accordingly.
     *
     * @param evt is a property change event
     */
    private void pollSQMEvents(PropertyChangeEvent evt) {
        if (evt.getPropertyName().contains("SQMLoad")) {
            resetInterface();
        }

        if (evt.getPropertyName().contains("SQMExecution")) {
            onSQMExecution(evt);
        }

        switch (evt.getPropertyName()) {
            case "SQMLoadSuccess":
                onSQMLoadSuccess(evt);

                break;

            case "SQMExecutionSuccess":
                onSQMExecutionSuccess(evt);

                break;

            case "SQMFailCountChanged":
                onSQMFailCountChanged(evt);

                break;

            case "SQMDescriptionIndexChanged":
                onSQMDescriptionIndexChanged(evt);

                break;
        }
    }

    /**
     * Checks whether an event is related to command navigation and takes action
     * accordingly.
     *
     * @param evt is a property change event
     */
    private void pollNavigationEvents(PropertyChangeEvent evt) {
        if (evt.getPropertyName().contains("CommandNavigation")) {
            TextField_Command.setText((String) evt.getNewValue());
        }

        if (evt.getPropertyName().equals("CommandLaunch")) {
            onCommandLaunch(evt);
        }
    }

    /**
     * Called whenever a exec is executed.
     */
    private void onSQMExecution(PropertyChangeEvent evt) {
        resetIndividualsList();
        resetVarInfoTable();
        resetGeometrySelectionComboBox();
        sceneController.resetDisplayInformation();
    }

    /**
     * Called when the exec manager is successfully loaded.
     */
    private void onSQMLoadSuccess(PropertyChangeEvent evt) {
        SQM sqm = (SQM) evt.getNewValue();
        String activeDirectoryPath = sqm.getPath();

        Label_StatusText.setText("Active directory: "
                + Paths.get(activeDirectoryPath).getFileName().toString());
        Label_StatusText.setToolTipText(activeDirectoryPath);
        TextField_Command.setEnabled(true);
        sceneController.resetDisplayInformation();

        JOptionPane.showMessageDialog(this, "Load complete.", "Info",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Called upon successful execution of a exec.
     */
    private void onSQMExecutionSuccess(PropertyChangeEvent evt) {
        List<SemanticCloudDescription> descriptions
                = (List<SemanticCloudDescription>) evt.getNewValue();

        sceneController.load(descriptions);

        DefaultListModel listModel = (DefaultListModel) List_Individuals.getModel();

        descriptions.forEach(description -> {
            listModel.addElement(description.toString());
        });
    }

    /**
     * Called whenever the fail count of the Semviz Query Manager changes.
     *
     * @param evt is a property change event
     */
    private void onSQMFailCountChanged(PropertyChangeEvent evt) {
        int failCount = (int) evt.getNewValue();

        if (failCount > 0) {
            JOptionPane.showMessageDialog(this, "A number of " + failCount + " cloud "
                    + "individuals could not be retreived.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Called whenever the selected description index is changed within the
     * Semviz Query Manager controller.
     *
     * @param evt is a property change event
     */
    private void onSQMDescriptionIndexChanged(PropertyChangeEvent evt) {
        resetVarInfoTable();

        int index = (int) evt.getNewValue();
        DefaultTableModel model = (DefaultTableModel) Table_VarInfo.getModel();

        if (index != -1) {
            // An individual is selected

            /*
            Filling in variable information table with the semantic attributes
            decribing the selected individual.
             */
            sqmController.getSelectedDescription().attributeKeySet().forEach(key -> {
                String[] row = new String[2];

                row[0] = key;
                row[1] = sqmController.getSelectedDescription().getAttribute(key);

                model.addRow(row);
            });

            sceneController.setDisplaySelection(index);
            ComboBox_GeometrySelection.setEnabled(true);
            ComboBox_GeometrySelection.setSelectedIndex(sceneController.getSelectedViewIndex(index));
        }
    }

    /**
     * Called whenever a SPARQL query is launched.
     *
     * @param evt is a property change event
     */
    private void onCommandLaunch(PropertyChangeEvent evt) {
        String queryString = (String) evt.getNewValue();

        SwingWorker<Void, Void> swingWorker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                sqmController.exec(queryString);

                return null;
            }
        };

        final JDialog dialog = new LoadingDialog(this);

        swingWorker.addPropertyChangeListener((PropertyChangeEvent evt1) -> {
            if (evt1.getPropertyName().equals("state")) {
                if (evt1.getNewValue() == SwingWorker.StateValue.DONE) {
                    dialog.dispose();
                }
            }
        });

        swingWorker.execute();

        dialog.setVisible(true);
    }

    public void exit() {
        setVisible(false);
        dispose();
        System.exit(0);
    }

}
